export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  SENDGRID_API_KEY ='SENDGRID_API_KEY',
  TWILIO_SID='TWILIO_SID',
  TWILIO_TOKEN='TWILIO_TOKEN'
}
